version: 2
updates:
  # Frontend NPM dependencies
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      dependency-type: "all"
    labels:
      - "dependencies"
      - "frontend"
    reviewers:
      - "frontend-team"
    versioning-strategy: "auto"

  # Backend NPM dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      dependency-type: "all"
    labels:
      - "dependencies"
      - "backend"
    reviewers:
      - "backend-team"
    versioning-strategy: "auto"

  # Python benchmark service dependencies
  - package-ecosystem: "pip"
    directory: "/src/backend/services/benchmark"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      dependency-type: "all"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "backend-team"
    versioning-strategy: "auto"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "devops-team"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ci-cd"
    reviewers:
      - "devops-team"